version: '3.8'

services:
  proxy:
    container_name: proxy
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - mariadb
      - core

  mariadb:
    container_name: 'mariadb'
    env_file:
      - .env
    image: mariadb:11.2
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      TZ: '${TZ}'
    volumes:
      - './.mariasql:/var/lib/mysql'
    networks:
      - backend
    ports:
      - '${MARIADB_PORT}:3306'
    restart: always

  core:
    container_name: core
    restart: always
    build:
      context: ../
      target: dependencies
    ports:
      - ${CORE_APP_PORT}:3333
    volumes:
      - ../:/home/node/app
    networks:
      - backend
    command: npm run dev

networks:
  backend:
    name: "backend"
    driver: bridge
